import { Ingredient } from '../../types';
import { normalizeFa } from '../textNormalize';

/**
 * دیتابیس ترکیبات.
 *
 * تغییر مهم نسبت به نسخه ۱: روابط با شناسه (id) نگهداری می‌شوند نه
 * متن آزاد. قبلاً تداخل‌سنج با includes() روی نام کار می‌کرد که هم
 * خطای کاذب می‌داد و هم تداخل‌های واقعی را رد می‌کرد. الان می‌توانیم
 * تداخل محصولات قفسه کاربر را هم حساب کنیم.
 */
export const INGREDIENTS_DATABASE: Ingredient[] = [
  {
    id: 'ing_niacinamide',
    activeClass: 'niacinamide',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_niacinamide.jpg',
    name: 'Niacinamide (Vitamin B3)',
    nameFa: 'نیاسینامید (ویتامین B3)',
    commonNamesFa: ['نیاسیناماید', 'ویتامین بی۳', 'نیاسین آمید', 'niacinamide', 'vitamin b3'],
    category: 'active',
    benefitsFa: ['تنظیم ترشح چربی پوست', 'کاهش التهاب و قرمزی جوش', 'کم‌رنگ کردن لک‌های تیره', 'کاهش ظاهر منافذ'],
    suitableSkinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive', 'dehydrated'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_zinc_pca', 'ing_ceramides', 'ing_salicylic_acid', 'ing_panthenol', 'ing_azelaic_acid'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['serum', 'moisturizer', 'cleanser', 'toner', 'sunscreen'],
    descriptionFa:
      'نیاسینامید یکی از ایمن‌ترین و محبوب‌ترین ترکیبات مراقبت از پوست است که سد دفاعی پوست را تقویت کرده و تولید سِبوم را متعادل می‌کند. برخلاف باور قدیمی، مطالعات تازه نشان داده مصرف همزمان با ویتامین C مشکلی ایجاد نمی‌کند.',
  },
  {
    id: 'ing_retinol',
    activeClass: 'retinoid',
    potency: 'moderate',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_retinol.jpg',
    name: 'Retinol (Vitamin A)',
    nameFa: 'رتینول (ویتامین A)',
    commonNamesFa: ['رتینول', 'ویتامین آ', 'retinol', 'vitamin a'],
    category: 'active',
    benefitsFa: ['تحریک کلاژن‌سازی', 'کاهش خطوط ریز و چروک', 'درمان جوش‌های سرسیاه و زیرپوستی', 'یکدست‌سازی بافت پوست'],
    suitableSkinTypes: ['oily', 'combination', 'normal', 'dry'],
    avoidSkinTypes: ['sensitive'],
    usageTime: 'night',
    pregnancySafety: 'avoid',
    breastfeedingSafety: 'avoid',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_niacinamide', 'ing_ceramides', 'ing_panthenol'],
    avoidCombiningIds: ['ing_salicylic_acid', 'ing_vitamin_c', 'ing_glycolic_acid', 'ing_lactic_acid', 'ing_benzoyl_peroxide', 'ing_tretinoin', 'ing_adapalene'],
    conflictReasonFa: 'مصرف همزمان با لایه‌بردارهای اسیدی سد دفاعی را تخریب می‌کند. یکی را صبح و دیگری را شب یا در شب‌های متفاوت استفاده کنید.',
    sideEffectsFa: 'در ۲ تا ۴ هفته اول ممکن است پوسته‌ریزی خفیف، خشکی یا سوزش ایجاد کند.',
    irritationRisk: 'high',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['serum', 'treatment', 'eyecare'],
    descriptionFa:
      'موثرترین ترکیب اثبات‌شده برای نوسازی سلولی. حتماً فقط شب‌ها استفاده شود و مصرف ضدآفتاب در روز بعد الزامی است. قبل از لیزر، پیلینگ و اپیلاسیون باید چند روز قطع شود.',
  },
  {
    id: 'ing_salicylic_acid',
    activeClass: 'bha',
    potency: 'moderate',
    typicalUse: 'both',
    imageUrl: '/assets/ingredients/ing_salicylic_acid.jpg',
    name: 'Salicylic Acid (BHA)',
    nameFa: 'سالیسیلیک اسید (BHA)',
    commonNamesFa: ['سالیسیلیک', 'بی اچ ای', 'BHA', 'اسید سالیسیلیک', 'salicylic acid'],
    category: 'exfoliant',
    benefitsFa: ['حل کردن چربی داخل منافذ', 'درمان جوش‌های سرسیاه و سرسفید', 'ضدالتهاب و آنتی‌باکتریال'],
    suitableSkinTypes: ['oily', 'combination'],
    avoidSkinTypes: ['dry', 'sensitive'],
    usageTime: 'both',
    pregnancySafety: 'consult_doctor',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_zinc_pca', 'ing_panthenol'],
    avoidCombiningIds: ['ing_retinol', 'ing_tretinoin', 'ing_adapalene', 'ing_glycolic_acid', 'ing_lactic_acid'],
    conflictReasonFa: 'دو لایه‌بردار قوی در یک روتین باعث تخریب سد دفاعی و قرمزی ماندگار می‌شود.',
    irritationRisk: 'moderate',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['cleanser', 'toner', 'serum', 'exfoliant', 'treatment'],
    descriptionFa: 'یک لایه‌بردار محلول در چربی که به عمق منافذ نفوذ کرده و انسدادهای چربی و سلول‌های مرده را حل می‌کند.',
  },
  {
    id: 'ing_glycolic_acid',
    activeClass: 'aha',
    potency: 'strong',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_glycolic_acid.jpg',
    name: 'Glycolic Acid (AHA)',
    nameFa: 'گلیکولیک اسید (AHA)',
    commonNamesFa: ['گلیکولیک', 'ای اچ ای', 'AHA', 'اسید گلیکولیک', 'glycolic acid'],
    category: 'exfoliant',
    benefitsFa: ['روشن‌سازی و شفافیت', 'یکدست کردن بافت و رنگ پوست', 'کمک به محو لک سطحی'],
    suitableSkinTypes: ['normal', 'combination', 'oily'],
    avoidSkinTypes: ['sensitive', 'dehydrated'],
    usageTime: 'night',
    pregnancySafety: 'consult_doctor',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: ['ing_retinol', 'ing_tretinoin', 'ing_adapalene', 'ing_salicylic_acid', 'ing_lactic_acid', 'ing_vitamin_c'],
    conflictReasonFa: 'مصرف همزمان چند اسید یا اسید با رتینول، ریسک سوزش و لک التهابی را بالا می‌برد.',
    irritationRisk: 'high',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['toner', 'exfoliant', 'serum'],
    descriptionFa: 'لایه‌بردار محلول در آب که سطح پوست را صیقل می‌دهد. حتماً شب و با ضدآفتاب روز بعد.',
  },
  {
    id: 'ing_hyaluronic_acid',
    activeClass: 'hydrator',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_hyaluronic_acid.jpg',
    name: 'Hyaluronic Acid',
    nameFa: 'هیالورونیک اسید',
    commonNamesFa: ['هیالورونیک', 'هیالورونیک اسید', 'HA', 'hyaluronic acid', 'هیالرونیک'],
    category: 'hydrator',
    benefitsFa: ['جذب و حفظ رطوبت', 'پرکردن خطوط ناشی از کم‌آبی', 'شاداب‌کننده فوری'],
    suitableSkinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive', 'dehydrated'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_retinol', 'ing_vitamin_c', 'ing_salicylic_acid', 'ing_ceramides', 'ing_panthenol', 'ing_azelaic_acid', 'ing_centella', 'ing_glycolic_acid', 'ing_zinc_pca'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['serum', 'moisturizer', 'mask'],
    descriptionFa: 'آب‌رسان قوی که رطوبت را به پوست می‌کشد. روی پوست نم‌دار بزنید و بلافاصله مرطوب‌کننده رویش بگذارید؛ در هوای خشک به تنهایی می‌تواند پوست را خشک‌تر کند.',
  },
  {
    id: 'ing_vitamin_c',
    activeClass: 'antioxidant',
    potency: 'moderate',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_vitamin_c.jpg',
    name: 'Vitamin C (L-Ascorbic Acid)',
    nameFa: 'ویتامین C (آنتی‌اکسیدان)',
    commonNamesFa: ['ویتامین سی', 'ویتامین C', 'اسید اسکوربیک', 'vitamin c', 'ال اسکوربیک اسید'],
    category: 'antioxidant',
    benefitsFa: ['خنثی‌سازی رادیکال‌های آزاد', 'روشن‌کننده و شفاف‌کننده', 'کمک به ساخت کلاژن', 'تقویت اثر ضدآفتاب'],
    suitableSkinTypes: ['dry', 'normal', 'combination', 'oily'],
    avoidSkinTypes: ['sensitive'],
    usageTime: 'morning',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_niacinamide', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: ['ing_retinol', 'ing_tretinoin', 'ing_adapalene', 'ing_glycolic_acid', 'ing_lactic_acid'],
    conflictReasonFa: 'با رتینول و اسیدهای قوی در یک نوبت مصرف نشود. ویتامین C مخصوص روتین صبح است.',
    irritationRisk: 'moderate',
    commonCategoryIds: ['serum', 'toner', 'moisturizer'],
    descriptionFa: 'سپر دفاعی روزانه پوست در برابر آلودگی و آفتاب. برای هوای آلوده شهرهای بزرگ کاملاً توصیه می‌شود.',
  },
  {
    id: 'ing_ceramides',
    activeClass: 'barrier',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_ceramides.jpg',
    name: 'Ceramides',
    nameFa: 'سرامیدها (ترمیم‌کننده سد دفاعی)',
    commonNamesFa: ['سرامید', 'سرامیدها', 'ceramide', 'ceramides'],
    category: 'barrier_repair',
    benefitsFa: ['ترمیم سد دفاعی آسیب‌دیده', 'جلوگیری از تبخیر رطوبت', 'کاهش سوزش و کشیدگی'],
    suitableSkinTypes: ['dry', 'sensitive', 'dehydrated', 'combination', 'normal', 'oily'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_retinol', 'ing_glycolic_acid', 'ing_salicylic_acid', 'ing_niacinamide', 'ing_hyaluronic_acid', 'ing_panthenol'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['moisturizer', 'cleanser', 'serum', 'toner'],
    descriptionFa: 'چسب طبیعی بین سلول‌های پوست. بعد از لیزر، پیلینگ و در روزهای قاعدگی بهترین انتخاب است.',
  },
  {
    id: 'ing_azelaic_acid',
    activeClass: 'azelaic',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_azelaic_acid.jpg',
    name: 'Azelaic Acid',
    nameFa: 'آزلائیک اسید',
    commonNamesFa: ['آزلائیک', 'آزلاییک اسید', 'azelaic acid', 'azelaic'],
    category: 'active',
    benefitsFa: ['کاهش قرمزی و رزاسه', 'کم‌رنگ کردن لک و ملاسما', 'ضدجوش ملایم'],
    suitableSkinTypes: ['sensitive', 'dry', 'oily', 'combination', 'normal'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_centella', 'ing_ceramides'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['serum', 'treatment'],
    descriptionFa:
      'گزینه طلایی برای پوست حساس، رزاسه و لک. تنها ترکیب موثر ضدلک که در بارداری هم معمولاً مجاز است؛ با این حال با پزشک خود مشورت کنید.',
  },
  {
    id: 'ing_centella',
    activeClass: 'soother',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_centella.jpg',
    name: 'Centella Asiatica (Cica)',
    nameFa: 'سنتلا آسیاتیکا (سیکا)',
    commonNamesFa: ['سیکا', 'سنتلا', 'cica', 'centella asiatica'],
    category: 'soother',
    benefitsFa: ['التیام‌بخش سریع', 'کاهش التهاب و سوزش', 'بازسازی بافت آسیب‌دیده'],
    suitableSkinTypes: ['sensitive', 'dry', 'oily', 'combination', 'normal', 'dehydrated'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_azelaic_acid', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['serum', 'moisturizer', 'mask', 'toner'],
    descriptionFa: 'ترکیب تسکین‌دهنده محبوب کره‌ای، مناسب برای روزهای پس از خدمات زیبایی و دوره قاعدگی.',
  },
  {
    id: 'ing_zinc_pca',
    activeClass: 'other',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_zinc_pca.jpg',
    name: 'Zinc PCA',
    nameFa: 'زینک پی‌سی‌ای',
    commonNamesFa: ['زینک', 'زینک پی سی ای', 'zinc pca', 'zinc'],
    category: 'active',
    benefitsFa: ['مات‌کننده چربی اضافی', 'ضدمیکروب عامل آکنه', 'کاهش ظاهر منافذ باز'],
    suitableSkinTypes: ['oily', 'combination'],
    avoidSkinTypes: ['dry'],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_salicylic_acid', 'ing_hyaluronic_acid'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['toner', 'serum', 'moisturizer'],
    descriptionFa: 'ترکیب زینک و عامل مرطوب‌کننده طبیعی پوست که چربی بی‌رویه را کنترل می‌کند.',
  },
  {
    id: 'ing_panthenol',
    activeClass: 'soother',
    potency: 'gentle',
    typicalUse: 'leave_on',
    imageUrl: '/assets/ingredients/ing_panthenol.jpg',
    name: 'Panthenol (Pro-Vitamin B5)',
    nameFa: 'پانتنول (پرو ویتامین B5)',
    commonNamesFa: ['پروویتامین بی۵', 'دکسپانتنول', 'panthenol', 'provitamin b5'],
    category: 'soother',
    benefitsFa: ['آب‌رسانی عمیق', 'تسکین خارش و سوزش', 'افزایش انعطاف‌پذیری پوست'],
    suitableSkinTypes: ['dry', 'sensitive', 'dehydrated', 'normal', 'combination', 'oily'],
    avoidSkinTypes: [],
    usageTime: 'both',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_ceramides', 'ing_centella', 'ing_retinol', 'ing_salicylic_acid'],
    avoidCombiningIds: [],
    irritationRisk: 'low',
    commonCategoryIds: ['moisturizer', 'serum', 'mask', 'cleanser', 'toner'],
    descriptionFa: 'پانتنول پس از جذب به ویتامین B5 تبدیل می‌شود و مانند مرهمی نرم، خشکی و التهاب را تسکین می‌دهد.',
  },
  {
    id: 'ing_lactic_acid',
    imageUrl: '/assets/ingredients/ing_lactic_acid.jpg',
    name: 'Lactic Acid (AHA)',
    nameFa: 'لاکتیک اسید (AHA ملایم)',
    commonNamesFa: ['لاکتیک اسید', 'لاکتیک', 'lactic acid'],
    category: 'exfoliant',
    activeClass: 'aha',
    potency: 'moderate',
    typicalUse: 'leave_on',
    benefitsFa: ['لایه‌برداری ملایم', 'افزایش رطوبت سطح پوست', 'یکدست کردن بافت'],
    suitableSkinTypes: ['normal', 'dry', 'combination', 'dehydrated'],
    // ملایم‌ترین AHA است، ولی همچنان AHA؛ پوست حساس باید احتیاط کند.
    avoidSkinTypes: ['sensitive'],
    usageTime: 'night',
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_panthenol', 'ing_ceramides', 'ing_niacinamide'],
    avoidCombiningIds: ['ing_retinol', 'ing_tretinoin', 'ing_adapalene', 'ing_glycolic_acid', 'ing_salicylic_acid'],
    conflictReasonFa: 'دو لایه‌بردار یا لایه‌بردار با رتینوئید در یک نوبت، ریسک سوزش را بالا می‌برد.',
    irritationRisk: 'moderate',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['toner', 'exfoliant', 'moisturizer'],
    descriptionFa:
      'ملایم‌ترین عضو خانواده AHA است و مولکول بزرگ‌تری دارد؛ به همین دلیل معمولاً کمتر از گلیکولیک اسید تحریک می‌کند.',
  },
  {
    id: 'ing_benzoyl_peroxide',
    imageUrl: '/assets/ingredients/ing_benzoyl_peroxide.jpg',
    name: 'Benzoyl Peroxide',
    nameFa: 'بنزویل پراکساید',
    commonNamesFa: ['بنزوئیل پراکساید', 'بنزوئیل', 'benzoyl peroxide', 'BP'],
    category: 'active',
    activeClass: 'benzoyl_peroxide',
    potency: 'strong',
    typicalUse: 'both',
    benefitsFa: ['کشتن باکتری عامل آکنه', 'کاهش جوش التهابی'],
    suitableSkinTypes: ['oily', 'combination', 'normal'],
    avoidSkinTypes: ['sensitive', 'dry'],
    usageTime: 'both',
    pregnancySafety: 'consult_doctor',
    breastfeedingSafety: 'consult_doctor',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_panthenol', 'ing_ceramides'],
    avoidCombiningIds: ['ing_retinol', 'ing_tretinoin', 'ing_adapalene', 'ing_vitamin_c'],
    conflictReasonFa: 'در یک نوبت با رتینوئید یا ویتامین C مصرف نشود؛ یکی را صبح و دیگری را شب بزن.',
    sideEffectsFa: 'خشکی، پوسته‌ریزی و بی‌رنگ کردن پارچه و حوله.',
    irritationRisk: 'high',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['cleanser', 'treatment'],
    descriptionFa: 'موثرترین گزینهٔ بدون نسخه برای جوش التهابی؛ با غلظت کم و یک شب در میان شروع کن.',
  },
  {
    id: 'ing_tretinoin',
    imageUrl: '/assets/ingredients/ing_tretinoin.jpg',
    name: 'Tretinoin (prescription retinoid)',
    nameFa: 'ترتینوئین (رتینوئید تجویزی)',
    commonNamesFa: ['ترتینوئین', 'رتین آ', 'retin a', 'tretinoin'],
    category: 'active',
    activeClass: 'retinoid',
    potency: 'strong',
    typicalUse: 'leave_on',
    prescriptionOnly: true,
    benefitsFa: ['درمان آکنه', 'نوسازی پوست', 'کاهش لک و چروک'],
    suitableSkinTypes: ['oily', 'combination', 'normal'],
    // تصحیح ممیزی: رتینولِ OTC ['sensitive'] داشت ولی ترتینوئین — که قوی‌ترین
    // رتینوئید این دیتابیس است — [] داشت. یعنی قاعده برعکس عمل می‌کرد.
    avoidSkinTypes: ['sensitive', 'dehydrated', 'dry'],
    usageTime: 'night',
    pregnancySafety: 'avoid',
    breastfeedingSafety: 'avoid',
    compatibleIngredientIds: ['ing_hyaluronic_acid', 'ing_ceramides', 'ing_panthenol', 'ing_niacinamide'],
    avoidCombiningIds: ['ing_glycolic_acid', 'ing_salicylic_acid', 'ing_lactic_acid', 'ing_benzoyl_peroxide', 'ing_vitamin_c'],
    conflictReasonFa: 'با لایه‌بردارهای اسیدی یا ویتامین C در یک نوبت مصرف نشود؛ یکی صبح و دیگری شب.',
    sideEffectsFa: 'در هفته‌های اول خشکی و پوسته‌ریزی طبیعی است.',
    irritationRisk: 'high',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['treatment'],
    descriptionFa:
      'رتینوئید تجویزی و قوی‌تر از رتینول بدون نسخه است. برنامهٔ مصرف و قطع آن را پزشک تعیین می‌کند، نه اپ.',
  },
  {
    id: 'ing_adapalene',
    imageUrl: '/assets/ingredients/ing_adapalene.jpg',
    name: 'Adapalene',
    nameFa: 'آداپالن',
    commonNamesFa: ['آداپالن', 'دیفرین', 'differin', 'adapalene'],
    category: 'active',
    activeClass: 'retinoid',
    potency: 'moderate',
    typicalUse: 'leave_on',
    benefitsFa: ['درمان جوش سرسیاه و زیرپوستی', 'تنظیم نوسازی سلولی'],
    suitableSkinTypes: ['oily', 'combination', 'normal'],
    // تصحیح ممیزی: هر رتینوئیدی روی پوست حساس و خشک ریسک تحریک دارد.
    avoidSkinTypes: ['sensitive', 'dehydrated'],
    usageTime: 'night',
    pregnancySafety: 'avoid',
    breastfeedingSafety: 'consult_doctor',
    compatibleIngredientIds: ['ing_niacinamide', 'ing_hyaluronic_acid', 'ing_ceramides', 'ing_panthenol'],
    avoidCombiningIds: ['ing_glycolic_acid', 'ing_lactic_acid', 'ing_salicylic_acid', 'ing_benzoyl_peroxide'],
    conflictReasonFa: 'همزمان با اسیدهای لایه‌بردار یا بنزویل پراکساید در یک نوبت توصیه نمی‌شود.',
    irritationRisk: 'moderate',
    pauseBeforeProcedures: true,
    commonCategoryIds: ['treatment'],
    descriptionFa: 'رتینوئیدی پایدارتر و معمولاً ملایم‌تر از ترتینوئین؛ اغلب برای آکنه تجویز می‌شود.',
  },
];

export function findIngredientById(id: string): Ingredient | undefined {
  return INGREDIENTS_DATABASE.find((item) => item.id === id);
}

/**
 * پیدا کردن ترکیب از یک متن آزاد (چیزی که کاربر دستی تایپ کرده).
 *
 * نسخهٔ قبل فقط تطبیق دقیق داشت و commonNamesFa را کاملاً نادیده می‌گرفت؛
 * یعنی «رتین آ» یا «Retinol» یا «هیالرونیک» هیچ‌وقت به ترکیب وصل نمی‌شد و
 * customIngredients عملاً از همهٔ قاعده‌ها جا می‌ماند. حالا سه مرحله:
 * تطبیق دقیق نرمال‌شده، بعد نام‌های رایج، بعد شامل‌بودن با طول امن.
 */
export function findIngredientByName(query: string): Ingredient | undefined {
  const needle = normalizeFa(query);
  if (!needle) return undefined;

  const namesOf = (item: Ingredient) =>
    [item.id, item.name, item.nameFa, ...(item.commonNamesFa || [])].map(normalizeFa).filter(Boolean);

  const exact = INGREDIENTS_DATABASE.find((item) => namesOf(item).includes(needle));
  if (exact) return exact;

  // تطبیق جزئی فقط برای متن‌های به‌قدر کافی بلند، وگرنه خطای کاذب می‌دهد.
  if (needle.length < 4) return undefined;
  return INGREDIENTS_DATABASE.find((item) =>
    namesOf(item).some((name) => name.length >= 4 && (name.includes(needle) || needle.includes(name))),
  );
}

/** همهٔ ترکیباتی که در یک متن آزاد (مثل فهرست ترکیبات یک محصول) پیدا می‌شوند. */
export function findIngredientsInText(text: string): Ingredient[] {
  const haystack = normalizeFa(text);
  if (!haystack) return [];
  return INGREDIENTS_DATABASE.filter((item) =>
    [item.name, item.nameFa, ...(item.commonNamesFa || [])]
      .map(normalizeFa)
      .some((name) => name.length >= 4 && haystack.includes(name)),
  );
}

/** همهٔ ترکیبات یک دسته (مانند همهٔ رتینوئیدها یا همهٔ AHAها). */
export function ingredientIdsOfClass(...classes: string[]): string[] {
  return INGREDIENTS_DATABASE.filter((item) => item.activeClass && classes.includes(item.activeClass)).map(
    (item) => item.id,
  );
}
